site_name: "Electronics design: The guide to good manners"
site_url: https://guide.eeinte.ch/
site_description: "Electronics design: The guide to good manners"
site_author: eeintech

# Repository
repo_url: https://github.com/eeintech/guide
repo_name: eeintech/guide

# Plugins
plugins:
  - search
  - glightbox

# Theme
theme:
  name: material
  custom_dir: _includes/overrides
  logo: assets/logo.png
  favicon: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.footer
    - navigation.top
    - toc.integrate
    - toc.follow

# Navigation
nav:
  - index.md
  - diagram.md
  - The schematics:
    - The component picking: s_pick.md
    - The symbols: s_symbol.md
    - The most intuitive circuits: s_circuit.md
  - The layout:
    - The placement: l_place.md
    - The contraints: l_constraint.md
    - The routing: l_route.md
  - review.md
  - validation.md

# Extensions
markdown_extensions:
  - toc:
      permalink: true