site_name: The Electronics Design Guide for Best Practices and Workflow

plugins:
  - glightbox

theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.indexes

nav:
  - index.md
  - Ideas and System Diagram: diagram.md
  - Pick Components: pick.md
  - Draw Circuit: draw.md
