site_name: "Electronics design: The guide to good manners"
repo_url: https://github.com/eeintech/guide
repo_name: eeintech/guide

plugins:
  - search
  - glightbox

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.indexes

nav:
  - index.md
  - Ideas and System Diagram: diagram.md
  - Schematics:
    - Right Component: s_pick.md
    - Obvious Symbol: s_symbol.md
    - Intuitive Circuit: s_circuit.md
  - Layout:
    - First Place: l_place.md
    - Then Contraint: l_constraint.md
    - At Last Route: l_route.md

# Extensions
markdown_extensions:
  - toc:
      permalink: true